acme_message:
    resource: "@AcmeMessageBundle/Resources/config/routing.yml"
    prefix:   /

acme_auth:
    resource: "@AcmeAuthBundle/Resources/config/routing.yml"
    prefix:   /

acme_resource:
    resource: "@AcmeResourceBundle/Resources/config/routing.yml"
    prefix:   /

acme_org:
    resource: "@AcmeOrgBundle/Resources/config/routing.yml"
    prefix:   /




