security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Acme\AuthBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:        
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        administrators:
                entity: { class: AcmeAuthBundle:User }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:  ^/auth/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /auth/login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /auth/role
                
            logout:
                path:   _demo_logout
                target: _demo
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
                
        admin_area:
            pattern: ^/auth
            security: true
            http_basic: ~                

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/auth/, roles: ROLE_ADMIN }
