parameters:
#    acme_organisation.example.class: Acme\OrganisationBundle\Example

services:
#    acme_organisation.example:
#        class: %acme_organisation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
